package com.kyweb.mapper;

import com.kyweb.model.TbQuartz;
import com.kyweb.model.TbQuartzExample;
import com.kyweb.vo.PageVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbQuartzMapper {

    List<TbQuartz> selectShowMessage(PageVo pageVo);
    int selectQuartzPage();
    int countByExample(TbQuartzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quartz
     *
     * @mbggenerated
     */
    int deleteByExample(TbQuartzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quartz
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quartz
     *
     * @mbggenerated
     */
    int insert(TbQuartz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quartz
     *
     * @mbggenerated
     */
    int insertSelective(TbQuartz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quartz
     *
     * @mbggenerated
     */
    List<TbQuartz> selectByExample(TbQuartzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quartz
     *
     * @mbggenerated
     */
    TbQuartz selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quartz
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbQuartz record, @Param("example") TbQuartzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quartz
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbQuartz record, @Param("example") TbQuartzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quartz
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbQuartz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_quartz
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbQuartz record);

    List<TbQuartz> getNeedRunQuartz(String currTime);

    void updateMessageStatusByPrimaryKey(TbQuartz tbQuartz);
}